### ISSUE TITLE
java.lang.RuntimeException

### ISSUE THREAD

**Issue by nikijaz** [RelativityMC/raknetify#10]
**Describe the bug**
The server does not successfully stop when GeyserMC and Raknetify are installed. GeyserMC is on a different port.

**To Reproduce**
1. Install GeyserMC and Raknetify
2. Stop the server

**Expected behavior**
The server stops successfully

**Runtime info (please complete the following information):**
 - OS: Ubuntu 20.04.4 LTS x86_64
 - Minecraft version: 1.19
 - Mod version: 0.1.0+alpha.4.10 devbuild

**Crash reports / logs**
https://mclo.gs/KPYRacm

**Other mods**
GeyserMC

**Checklist**
 - [x] I am using the official version of the mod. 
 - [x] I tried the latest development version but the issue persists. 
 - [x] I searched for similar open issues and could not find an existing bug report on this. 

**Additional context**
This happens when you try to stop the server with /stop.

**Comment by ishland** [comment]
Looks like there is something wrong with the JAR download. Can you try redownload raknetify and try again?

**Comment by nikijaz** [comment]
Oh, yep, that helped. Thank you!
