### ISSUE TITLE
Failed to initialize a channel. Closing: [id: 0x1d4ab1dd, L:/192.168.0.5:30000 ! R:/46.164.218.151:2322] java.util.NoSuchElementException: timeout

### ISSUE THREAD

**Issue by Irowynn** [RelativityMC/raknetify#11]
**Describe the bug**
I can't connect to the server and I see error in console (ports are open and I can connect without raknet)

**To Reproduce**
1. Start server
2. Wait ~10 seconds
3. See error

**Expected behavior**
No error in console + successful connection

**Screenshots**
![image](https://user-images.githubusercontent.com/55800050/179423013-fe054175-aae1-40f8-a921-29485a053736.png)

**Runtime info (please complete the following information):**
 - OS: Windows 10 (Host) & Windows 11 (Client)
 - Minecraft version: 1.19 (Both Host and Client)
 - Mod version: Raknetify BungeeCord 0.1.0+alpha.5.0 (Host) & raknetify-fabric-0.1.0+alpha.5.0-all.jar (Client)
 - Mod branch: (fill this if you are not using the default `ver` branches)

**Crash reports / logs**
https://pastebin.com/myuREyad

**Other mods**
No other plugins (Host)
No other plugins (Client)

**Checklist**

 - [x] I am using the official version of the mod. 
 - [x] I tried the latest development version but the issue persists. 
 - [x] I searched for similar open issues and could not find an existing bug report on this. 

**Additional context**

**Comment by MineForce899** [comment]
Also tried with BungeeCord instead of WaterFall but it didn't help

**Comment by ishland** [comment]
It works fine for me on both BungeeCord b1654 and Waterfall b498 on Debian 11 on both sides. Can you try updating your BungeeCord and Waterfall?

**Comment by MineForce899** [comment]
BungeeCord/Waterfall is already on latest version
Firewall is disabled & server port opened in router (I have 30000 port for server and I **can** connect with example.com:30000 but I **can't** connect with raknet;example.com:30000

**Comment by ishland** [comment]
That's pretty weird. Can you upload your full BungeeCord setup here?

**Comment by MineForce899** [comment]
What you mean by "BungeeCord setup"? config.yml file?
[config.txt](https://github.com/RelativityMC/raknetify/files/9131579/config.txt)

**Comment by ishland** [comment]
I mean the folder running your BungeeCord server.
