### ISSUE TITLE
Mixin transformation of ServerLoginNetworkAddon fails with Fabric API 0.58.5

### ISSUE THREAD

**Issue by AViewFromTheTop** [RelativityMC/raknetify#13]
**Describe the bug**
With Raknetify and Fabric API 0.58.5, it's impossible to join servers and singleplayer worlds.

**To Reproduce**
1. Try to join a server or singleplayer world.
2. Unable to join, log says that Raknet's Mixin for Fabric API's ServerLoginNetworkAddon failed.

**Expected behavior**
You'd be able to join singleplayer and multiplayer worlds normally.

**Screenshots**
![2022-08-03_06 47 19](https://user-images.githubusercontent.com/87103914/182590621-63c4049a-f614-43cc-b776-bf9b11d92d52.png)

**Runtime info (please complete the following information):**
 - Windows 10
 - 1.19.1
 - Raknetify Fabric 0.1.0 Alpha 5.4

**Crash reports / logs**
03.08 10:47:58 [Server] Netty Epoll Server IO #2/INFO [STDERR]: java.lang.RuntimeException: Mixin transformation of net.fabricmc.fabric.impl.networking.server.ServerLoginNetworkAddon failed

**Other mods**
Fabric Api 0.58.5

**Checklist**

 - [x] I am using the official version of the mod. 
 - [x] I tried the latest development version but the issue persists. 
 - [x] I searched for similar open issues and could not find an existing bug report on this.

**Comment by ishland** [comment]
This is not a valid logs. Please paste full logs.

**Comment by AViewFromTheTop** [comment]
> This is not a valid logs. Please paste full logs.

[2022-08-03-3.log](https://github.com/RelativityMC/raknetify/files/9250651/2022-08-03-3.log)
Says something about the Mixin already being redirected by Fabric API itself up at the top.

**Comment by ishland** [comment]
Try adding `-Draknetify.debug=true` to your server jvm flags and reproduce this again.

**Comment by AViewFromTheTop** [comment]
> Try adding `-Draknetify.debug=true` to your server jvm flags and reproduce this again.

Just tried, I don't think the output is any different. I ran it on a singeplayer world this time since Apex doesn't let me modify server arguments, but I still get the same error nonetheless.
[latest.log](https://github.com/RelativityMC/raknetify/files/9250718/latest.log)

**Comment by ishland** [comment]
I don't think you have actually added the flag correctly. Also the version shown in the startup log is `0.1.0+alpha.5.2` rather than `0.1.0+alpha.5.4`.

**Comment by AViewFromTheTop** [comment]
> I don't think you have actually added the flag correctly. Also the version shown in the startup log is `0.1.0+alpha.5.2` rather than `0.1.0+alpha.5.4`.

I'm using a5.4 and the log doesn't mention otherwise. My jvm flags look like this, though I'll try it again:
-Draknetify.debug=true -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M

**Comment by ishland** [comment]
Your log did mention it is `0.1.0+alpha.5.2`
![image](https://user-images.githubusercontent.com/30385023/182594586-8c0de7a4-a525-47e7-81e0-0708beed86f8.png)

**Comment by AViewFromTheTop** [comment]
> Your log did mention it is `0.1.0+alpha.5.2` ![image](https://user-images.githubusercontent.com/30385023/182594586-8c0de7a4-a525-47e7-81e0-0708beed86f8.png)

The newer log doesn't, and I get the same issue. Here's another one.
[latest.log](https://github.com/RelativityMC/raknetify/files/9250768/latest.log)
