### ISSUE TITLE
Velocity Plugin Incompatibility: LimboAPI (+ LimboAuth and/or LimboFilter)

### ISSUE THREAD

**Issue by CamperSamu** [RelativityMC/raknetify#15]
### **Describe the bug**
Everytime you try to login on a 1.19.2/1.19.2-compatible server via Raknet the client crashes due to a OOB exception on a login packet.

### **To Reproduce**
1. Host a Velocity + Paper/Quilt 1.19.2 server (my Quilt backend has raknetify)
2. Try to join
3. Get disconnected.

### **Expected behavior**
The client should join without problems.

### **Screenshots**
![image](https://user-images.githubusercontent.com/32773961/184546022-f0ae5902-4b3a-4a9d-967c-5e2b955020eb.png)
![image](https://user-images.githubusercontent.com/32773961/184546034-6f85bfd5-fc30-41b5-b621-4952d839cba9.png)

### **Runtime info (please complete the following information):**
 - OS: Windows 10 21H1 (19043.1826)
 - Minecraft version: 1.19.2
 - Mod version: 0.1.0-alpha.5.12 (happens on older versions too)

### **Crash reports / logs**
[Netty Client Crash](https://paste.gg/p/anonymous/447c0e03413546de99bbaa15cf794be5)

### **Other mods**
[Client Modlist](https://paste.gg/p/anonymous/00024ec5562141adb37cedb786df9580)
[Velocity Proxy Plugins](https://paste.gg/p/anonymous/5ec8db32aecb4d02adb7e315b2a4d783)

### **Checklist**
 - [x] I am using the official version of the mod. 
 - [x] I tried the latest development version but the issue persists. 
 - [x] I searched for similar open issues and could not find an existing bug report on this.

**Comment by CamperSamu** [comment]
On the proxy side I get no errors outside of my disconnection (even with velocity's debug packets java arg).

**Comment by ishland** [comment]
Add jvm flag `-Draknetify.debug=true` to velocity and your client and try reproduce again.

**Comment by CamperSamu** [comment]
Velocity now reports invalid packet IDs for 1.19.1 and the client throws OOBs on packet decoding (because "channelHandler is null"

- [Velocity Log (from ping to me forcing the disconnection)](https://paste.gg/p/anonymous/45b52a032f82467e8c125ed327d48a86)
- [Client Log (full)](https://github.com/RelativityMC/raknetify/files/9338249/latest.log)

**Comment by ishland** [comment]
Try setting compression threshold to -1 on all backend servers.

**Comment by CamperSamu** [comment]
Sadly it doesn't do the trick, still getting the same issues...
I even tried removing Debugify and Krypton, but nothing

**Comment by CamperSamu** [comment]
Ok I finally discovered the issue.
Apparently there's an incompatability between LimboAPI plugins on Velocity with Raknetify.
I don't know what is causing it in the detail, but it might be because of LimboAuth (which I need because it has a cool feature that allows me and my staff to be notified by Telegram and Discord when they log in and kick the player in case it got hacked)

I'll open a issue over https://github.com/Elytrium/LimboAPI and rename this one then.

**Comment by CamperSamu** [comment]
This issue has been fixed: https://github.com/Elytrium/LimboAPI/issues/61
If someone finds any issues I'll open back the issue.
