### ISSUE TITLE
Simple Voice Chat incompatible ( Same UDP Port )

### ISSUE THREAD

**Issue by SpigotDE** [RelativityMC/raknetify#16]
[latest.log](https://gist.github.com/SpigotDE/f8f43fe0aa382ffd4b00210622d88eea)

**Comment by SpigotDE** [comment]
Does Raknetify needs the same port as the server? Or could we open another port for Raknetify

**Comment by nikijaz** [comment]
> Does Raknetify needs the same port as the server? Or could we open another port for Raknetify

"You need to have a UDP port opened at the same port number of your normal server port."

**Comment by SpigotDE** [comment]
I changed "Simple Voice Chat" UDP to another port, now i try Raknetify

**Comment by ishland** [comment]
Changing port number of raknetify just doesn't sound right or make any sense for me. 
If you are really looking for an option to change the port number, you have to add an additional JVM flag: `-Draknetify.fabric.portOverride=<port>` where `<port>` is the port number you want.

**Comment by SpigotDE** [comment]
All good, Simple Voice Chat allows to change the port to whereever, so now the server starts

Btw my log goes kinda crazy right now with Raknetify, can you quickly look over this pls

[latest.log](https://gist.github.com/SpigotDE/f5231df41f9c5205c6c46b2116e4d75a)

**Comment by SpigotDE** [comment]
Line 301
Line 324 - 335
Line 516 - 570

**Comment by ishland** [comment]
This looks like some other mods leaking memory or just a vanilla bug. It is made visible with raknetify.

**Comment by SpigotDE** [comment]
I have Memory Leak Fix installed

**Comment by ishland** [comment]
> I have Memory Leak Fix installed

Memory Leak Fix doesn't magically fixes everything.

**Comment by SpigotDE** [comment]
could i supress the L525-570 somehow?

**Comment by ishland** [comment]
Use `-Dio.netty.leakDetectionLevel=disabled` if you really want to silence that but this is usually not recommended.
