### ISSUE TITLE
Server blocks all udp connections if someone disconnects unexpectedly

### ISSUE THREAD

**Issue by siyy123** [RelativityMC/raknetify#27]
**Describe the bug**
Server blocks all udp connections and would never allow anyone to connect via raknet if someone disconnects unexpectedly (timeout or change of address ex. ipv6 mobility)

**To Reproduce**
1. start a server
2. connect and then change ip address (for example to make the player disconnect unexpectedly)
3. client gets disconnected due to connection loss
4. server still maintains the connection
5. server get connection timeout
6. server now refuses anyone to connect

**Expected behavior**

server should terminate the connection normally and allow normal operation rather than block all the connection through raknet.

**Runtime info (please complete the following information):**
 - OS: CentOS 9 Stream x86_64
 - Minecraft version: 1.18.2
 - Mod version: 0.1.0+alpha.5.54 devbuild
 - Mod branch: (fill this if you are not using the default `ver` branches)

**Checklist**

 - [x] I am using the official version of the mod. 
 - [x] I tried the latest development version but the issue persists. 
 - [x] I searched for similar open issues and could not find an existing bug report on this.

**Comment by siyy123** [comment]
whats more, when this issue happens, server would never shutdown if a stop command is entered. server would always suck at Stopping Server, and nerver gets shutdowned.

**Comment by ishland** [comment]
Try reproduce with latest devbuild first.

**Comment by siyy123** [comment]
tested on latest version issue remains

**Comment by ishland** [comment]
Try getting a `jstack -l <pid>` output when the issue occurs.

**Comment by siyy123** [comment]
Seems the latest version is ok now, i don't know why it's not working the first time.
