### ISSUE TITLE
Opening the creative inventory or switching armors causes a disconnect

### ISSUE THREAD

**Issue by ShadowShok** [RelativityMC/raknetify#29]
**Describe the bug**
Can't open the creative inventory, or switch armors by clicking on the inventory with another armor 

**To Reproduce**
1. Start a server with velocity
2. `/gamemode creative`
3. Open the inventory
4. Disconnected
OR
1. Join
2. Change you armor by dragging a piece of armor on top of the equipped one and equipping it(Unequipping the armor and wearing the other one in two clicks does not cause a disconnect)
3. Disconnected

**Videos**
https://user-images.githubusercontent.com/51331963/226195678-ef815ca2-eba2-43af-90a3-944a19dccb1b.mp4
https://user-images.githubusercontent.com/51331963/226195679-4308f3b7-c101-4445-a0de-405f6c2ba71a.mp4

**Runtime info (please complete the following information):**
 - OS: Windows 11
 - Minecraft version: 1.19.3 (ViaVersion on the server)
 - Mod version: 0.1.0+alpha.5.61+velocity
 - Additional plugins used on the proxy: floodgate, geyser

**Crash reports / logs**
https://pastebin.com/GFDNWhRu

**Comment by ShadowShok** [comment]
I tried with waterfall and it doesn't happen.
It's just a velocity issue.

**Comment by ishland** [comment]
Try reproduce with latest devbuild and see if it still happens.
