### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by wicivo** [RelativityMC/raknetify#30]
**Describe the bug**
Unmountable item on the client side, which disappears when reconnecting to the server

**To Reproduce**
It happens randomly

**Expected behavior**

**Screenshots**

**Runtime info (please complete the following information):**
 - OS: Server-Ubuntu, Client-Windows
 - Minecraft version: 1.19.4
 - Mod version: 0.1.0+alpha.5.62 devbuild
 - Mod branch: (fill this if you are not using the default `ver` branches)

**Crash reports / logs**
> [Raknetify Epoll #7/INFO]: [STDERR]: Raknetify: Warning: unknown packet type net/minecraft/class_8042 (net.minecraft.class_8042) for raknet multi-channel

**Other mods**
```
alternate-current-mc1.19-1.5.0.jar       emotecraft-for-MC1.19.3-2.2.7-b.build.47-fabric.jar  krypton-0.2.2.jar                          servercore-1.3.5-1.19.4.jar
anti-xray-1.3.0-Fabric-1.19.4.jar        fabric-api-0.76.0+1.19.4.jar                         ledger-1.2.7.jar                           smoothboot-fabric-1.19.4-1.7.0.jar
armor-stand-editor-2.1.0+1.19.4-rc2.jar  fabric-carpet-1.19.4-1.4.101+v230319.jar             lithium-fabric-mc1.19.4-0.11.1.jar         spark-1.10.34-fabric.jar
audioplayer-1.19.4-1.5.0.jar             fabric-language-kotlin-1.9.2+kotlin.1.8.10.jar       luckperms                                  styledplayerlist-2.3.0+1.19.3.jar
chunksending-fabric-1.19-2.5.jar         fabrictailor-2.0.2.jar                               LuckPerms-Fabric-5.4.67.jar                toggleableitemframes-2.1.1-1.19.x.jar
Chunky-1.3.53.jar                        Fastload+1.19.3-2.6.11.jar                           minimotd-fabric-mc1.19.4-2.0.11.jar        vcinteraction-1.19.4-1.0.3.jar
discord4fabric-1.19.4-1.10.3.jar         ferritecore-5.2.0-fabric.jar                         no-portals-1.19.3-1.0.1.jar                vmp-fabric-mc1.19.4-0.2.0+beta.7.64-all.jar
EasyAuth                                 fsit-v1.0.0.jar                                      phosphor-fabric-mc1.19.x-0.8.1.jar         voicechat-fabric-1.19.4-2.3.28.jar
easyauth-mc1.19.4-3.0.0-15.jar           InvView-1.4.10-1.19.3+.jar                           raknetify-fabric-0.1.0+alpha.5.61-all.jar
```

**Checklist**

 - [ ] I am using the official version of the mod. 
 - [ ] I tried the latest development version but the issue persists. 
 - [ ] I searched for similar open issues and could not find an existing bug report on this. 

**Additional context**

**Comment by NerdTo** [comment]
![image](https://user-images.githubusercontent.com/116191734/227309189-fa3fa577-350d-44cb-a1d6-6765c66cee74.png)

**Comment by ishland** [comment]
Logs is incomplete. Please paste the entire log.

**Comment by ishland** [comment]
Tracked in #49
