### ISSUE TITLE
[Feature Request] Add automatic detection of supported MTUs to the protocol.

### ISSUE THREAD

**Issue by 8MiYile** [RelativityMC/raknetify#31]
Add automatic detection of supported MTUs to the protocol.
The protocol header for auto-detection is `raknet`
Protocol header for low MPU `raknet:` was changed to `raknetl:`
Protocol header for high MPU `raknetl:` was changed to `rakneth:`

**Comment by ishland** [comment]
Automatic MTU discovery is already there by sending "Open Connection Request 1" with ever decreasing MTU until the server responds. `raknetl;` is mostly for setting the maximum MTU for this discovery process.
