### ISSUE TITLE
memory leaks on server

### ISSUE THREAD

**Issue by jitterdev** [RelativityMC/raknetify#32]
**Describe the bug**
server leaks memory rapidly

**To Reproduce**
1. ???
2. memory leak
3. server runs out of memory and crashes

**Expected behavior**
server doesnt memory leak

**Runtime info (please complete the following information):**
 - OS: Linux (amd64) version 4.15.0-208-generic
 - Minecraft version: 1.19.2
 - Mod version: (Fabric) 0.1.0+alpha.5.66
 - Mod branch: N/A

**Crash reports / logs**
https://mclo.gs/VTt6fzi (log)
https://mclo.gs/6qJJBOq (crash report)

**Other mods**
check the crash report above

**Checklist**
 - [x] I am using the official version of the mod. 
 
 ^ testing this atm, not sure if it fixed anything yet though

 - [x] I tried the latest development version but the issue persists. 

^ testing this atm, not sure if it fixed anything yet though

 - [x] I searched for similar open issues and could not find an existing bug report on this. 

**Additional context**
spark heap summary https://spark.lucko.me/5CQALSqQXO

line 9290 of the log seems to be of signifigance here

**Comment by jitterdev** [comment]
still seems to happen on the latest build https://mclo.gs/LBVKLHF

**Comment by ishland** [comment]
The memory leak appears to be coming from something else. Try removing `bluemap` and see if it still happens. 
Also add `-XX:+HeapDumpOnOutOfMemoryError` to the jvm flags and provide the `.hprof` file generated if it still happens.

**Comment by ishland** [comment]
> still seems to happen on the latest build https://mclo.gs/LBVKLHF

This does not indicate an out of memory and is running completely normal.
