### ISSUE TITLE
Error loading class

### ISSUE THREAD

**Issue by adiif1** [RelativityMC/raknetify#34]
**Describe the bug**
When turning on, the following error pops up

**To Reproduce**
1. Turn server with this mod

**Expected behavior**

**Screenshots**

**Runtime info (please complete the following information):**
 - OS: Ubuntu 22.04
 - Minecraft version: 1.18.2 ( FABRIC )
 - Mod version: 0.10 Alpha 5.72
 - Mod branch: (fill this if you are not using the default `ver` branches)

**Crash reports / logs**
`[00:56:44] [main/INFO]: =======================================================
[00:56:44] [main/INFO]: Applying mixin: MixinMinecraftServer...
[00:56:44] [main/WARN]: Error loading class: org/quiltmc/qsl/networking/impl/server/ServerLoginNetworkAddon (java.lang.ClassNotFoundException: `org/quiltmc/qsl/networking/impl/server/ServerLoginNetworkAddon)``

**Other mods**
I tru test without other mod

**Checklist**

 - [X] I am using the official version of the mod. 
 - [X] I tried the latest development version but the issue persists. 
 - [X] I searched for similar open issues and could not find an existing bug report on this. 

**Additional context**

**Comment by ishland** [comment]
This is completely harmless. This is from quilt compatibility and we cannot silence these warnings.
