### ISSUE TITLE
Publish 1.20 on Modrinth

### ISSUE THREAD

**Issue by NotNite** [RelativityMC/raknetify#35]
Heya! This mod is great, much thanks for it. My friend group's honored tradition of "survival Minecraft server once every major update" is on again, and Raknetify is enabling people with poor network latency/throughput to play along. Thank you! <3

My server is currently using the [GitHub Actions artifact](https://github.com/RelativityMC/raknetify/actions/runs/5202031651) (specifically the Fabric jar) inside of a [Packwiz](https://github.com/packwiz/packwiz) instance. This is working fantastically, but I'd prefer if the mod was published to a mod site like Modrinth. I'm trying to cut down on the amount of jars without sources in my modpacks due to the events of [Fractureiser](https://github.com/fractureiser-investigation/fractureiser), and I can't link to a GHA artifact directly from Packwiz because they require authentication to download.

If it's not too much hassle, could the latest version be published on Modrinth? Thanks!

**Comment by ishland** [comment]
It is already on modrinth. 
https://modrinth.com/plugin/raknetify/versions
