### ISSUE TITLE
Question: Is this compatible with Krypton?

### ISSUE THREAD

**Issue by vico93** [RelativityMC/raknetify#36]
Can i use both or should i choose one (or even Raknetify achieve the same optimization on its own)?

[Github](https://github.com/astei/krypton) | [Modrinth](https://modrinth.com/mod/krypton)

**Comment by ishland** [comment]
They are compatible with each other. However, the networking stack optimizations of Krypton does not apply to Raknetify connections.

**Comment by CuteistFox** [comment]
shouldent this be closed?
