### ISSUE TITLE
Cannot start local game with 0.1.0+alpha.5.109 and above

### ISSUE THREAD

**Issue by PoneyClairDeLune** [RelativityMC/raknetify#45]
**Describe the bug**
When trying to start a LAN world, there would only be an error message.

**To Reproduce**
1. Install Raknetify 0.1.0+alpha.5.109 or above in a Fabric Minecraft 1.20.1 installation.
2. Open a world and try starting a LAN game

**Expected behavior**
A message appears in chat: "Unable to start local game".

**Screenshots**
![image](https://github.com/RelativityMC/raknetify/assets/88174309/0c953495-c64b-456a-a0dd-864dc7588caa)

**Runtime info (please complete the following information):**
- OS: Linux amd64
- Minecraft version: 1.20.1
- Mod version: 0.1.0+alpha.5.109 to 0.1.0+alpha.5.114 
- Mod branch: dev

**Crash reports / logs**
N/A

**Other mods**
https://github.com/team-cloudchaser/mist-1-20-1/tree/main/.minecraft/versions/1.20.1%20Fabric%20Baseline/mods

**Checklist**
- [x] I am using the official version of the mod. 
- [ ] I tried the latest development version but the issue persists. 
- [x] I searched for similar open issues and could not find an existing bug report on this. 

**Additional context**
N/A

**Comment by ishland** [comment]
Cannot reproduce on 1.20.1 with `0.1.0+alpha.5.114`. Please provide logs and try getting a minimum set of mods reproducible.

**Comment by PoneyClairDeLune** [comment]
> Cannot reproduce on 1.20.1 with `0.1.0+alpha.5.114`. Please provide logs and try getting a minimum set of mods reproducible.

No longer reproducible on my side either. Nothing changed at all.
