### ISSUE TITLE
[Crash] Client - Fabric 1.20.6

### ISSUE THREAD

**Issue by bruh1273** [RelativityMC/raknetify#50]
**Describe the bug**
There's an incompatibility with ViaFabricPlus on the client side, with the `MultiplayerServerListPinger` mixin. 
**To Reproduce**
1. Install Fabric 1.20.6 for client
2. Add in Raknetify and ViaFabricPlus
3. Try to go to the multiplayer screen

**Expected behavior**

Game doesn't crash

**Screenshots**

**Runtime info (please complete the following information):**
 - OS: Windows 10 x64
 - Minecraft version: 1.20.6
 - Mod version: 0.1.0+alpha.5.123 devbuild
 - Mod branch: (fill this if you are not using the default `ver` branches)

**Crash reports / logs**

https://mclo.gs/Edyca83

**Other mods**

ViaFabricPlus

**Checklist**

 - [ ] I am using the official version of the mod. 
 - [x] I tried the latest development version but the issue persists. 
 - [x] I searched for similar open issues and could not find an existing bug report on this. 

**Additional context**

**Comment by Onako2** [comment]
Could reproduce on 0.1.0+alpha.5.128 with 1.21

`@Redirect conflict. Skipping viafabricplus.mixins.json:base.perserverversion.MixinMultiplayerServerListPinger from mod viafabricplus->@Redirect::replaceDefaultPort(Ljava/lang/String;)Lnet/minecraft/class_639; with priority 1000, already redirected by raknetify-fabric.mixins.json:client.MixinMultiplayerServerListPinger from mod raknetify->@Redirect::modifyRaknetAddress(Ljava/lang/String;)Lnet/minecraft/class_639; with priority 1010`

**Comment by FlorianMichael** [comment]
Should be fixed with https://github.com/ViaVersion/ViaFabricPlus/commit/f99845314afad3091ac505019b4d7f29bf5f9470

**Comment by ishland** [comment]
Fixed in ViaFabricPlus. Closing as resolved.
