### ISSUE TITLE
Issues with latest Velocity build

### ISSUE THREAD

**Issue by Neubulae** [RelativityMC/raknetify#8]
**Describe the bug**
Use latest Velocity(#161 so far) and the plugin won't load

**Runtime info (please complete the following information):**
 - OS: Arch Linux
 - Minecraft version: 1.18.2
 - Mod version: alpha 4.16

**Crash reports / logs**
https://0x0.st/oQvK.txt

**Checklist**

 - [x] I am using the official version of the mod. 
 - [x] I tried the latest development version but the issue persists. 
 - [x] I searched for similar open issues and could not find an existing bug report on this.

**Comment by Neubulae** [comment]
Pasting the utils directly into the Velocity jar circumvents the issue, but jarmodding is not a safe way to do. I tried compiling a shadowed jar but no luck either:
![图片](https://user-images.githubusercontent.com/24774842/177921238-283f34e1-8a40-43e2-974c-41d2e620e9cb.png)

**Comment by ishland** [comment]
[Please read the release notes.](https://github.com/RelativityMC/raknetify/releases/tag/0.1.0%2Balpha.4)

This is a velocity issue and the fix is waiting to be merged: PaperMC/Velocity#723

**Comment by ishland** [comment]
I added a workaround for velocity in latest devbuild. Can you give it a try?

**Comment by Neubulae** [comment]
All good
