### ISSUE TITLE
Potential memory leak?

### ISSUE THREAD

**Issue by Neubulae** [RelativityMC/raknetify#9]
**Describe the bug**
After prolonged connection, the player eventually runs out of memory. The problem doesn't exist outside a Raknet connection, and, once the problem happens, it prevents player from further rejoining the server again with Raknet, only restarting the game works.

**To Reproduce**
1. Join server with Raknet
2. Idle
3. Gets kicked

**Screenshots**
![图片](https://user-images.githubusercontent.com/24774842/177920592-2808cacd-a31a-46a0-839a-191b4892882e.png)

**Runtime info (please complete the following information):**
 - OS: Arch Linux
 - Minecraft version: 1.18.2
 - Mod version: alpha 4.16

**Crash reports / logs**
https://0x0.st/oQly.txt

**Other mods**
https://0x0.st/oQlt.txt

**Checklist**

 - [x] I am using the official version of the mod. 
 - [x] I tried the latest development version but the issue persists. 
 - [x] I searched for similar open issues and could not find an existing bug report on this.

**Comment by IAmSneak** [comment]
ive gotten the same issue in 1.19 versions using the official version of the mod and latest development

**Comment by ishland** [comment]
Try reproduce with jvm flag ` -Dio.netty.leakDetection.level=advanced`

**Comment by IAmSneak** [comment]
common mods:
- axes are weapons
- blastproof netherite
- carpet / extra / tis
- cloth config
- couplings
- fapi
- ferritecore
- krypton
- lazydfu
- lithium
- starlight
- raknetify (obviously)

**Comment by Neubulae** [comment]
As the log is extremely big I'll just paste it here https://0x0.st/oQhi.log

**Comment by ishland** [comment]
Try reproduce again with latest devbuild.

**Comment by Neubulae** [comment]
> Try reproduce again with latest devbuild.

reproduces, do I need to provide a log again?

**Comment by ishland** [comment]
> reproduces, do I need to provide a log again?

Yes definitely

**Comment by Neubulae** [comment]
it will take some time to reproduce a log, brb

**Comment by ishland** [comment]
Try reproduce with latest devbuild and provide logs if it still leaks.

**Comment by Neubulae** [comment]
the log is no longer spammed by things now so I think it's now fine? I'll wait and see

**Comment by Neubulae** [comment]
I don't reproduce with the latest build, thx pal.

**Comment by ishland** [comment]
Remember to remove the flag since the advanced leak detector comes with some performance overhead.
